name: decision-transformer-test
channels:
- pytorch
- conda-forge
dependencies:
- python=3.7.9
- pytorch
- cudatoolkit=11.3
- numpy
- psutil
- opencv
- pip
- atari_py
- pip:
  - pyprind
  - tensorflow-gpu
  - absl-py
  - gin-config==0.4
  - gym
  - tqdm
  - blosc
  - pillow
